security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: wangsm
      client-secret: 123456
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      id: rid
      # 获得 Token 信息的 URL
      token-info-uri: http://127.0.0.1:9004/oauth/check_token
    # 访问令牌获取 URL，自定义的
    access-token-uri: http://127.0.0.1:9004/oauth/token